from __future__ import annotations

from copy import deepcopy
from typing import Any

from .local_response_agent_metadata import (
    LOCAL_RESPONSE_AGENT_COUNT,
    build_local_agent_request_template,
    discovery_metadata_for_agent,
    enrich_local_response_agent,
    get_local_agent_metadata,
    list_local_agent_categories,
    preview_manual_agent_workflow,
    preview_local_agent_route,
    validate_catalog_consistency,
)
from .web_research import WEB_CONTEXT_RESPONSE_LIMITATIONS, WEB_RESEARCH_AGENT_MODE, WEB_RESEARCH_LIMITATIONS


LOCAL_RESPONSE_AGENTS_INDEX: list[dict[str, Any]] = [
    {
        "name": "Local Research Agent",
        "endpoint": "POST /agents/research/local-brief",
        "status": "implemented_local_only",
        "mode": "local_only_user_provided_notes",
        "docsLink": "/docs/local-research-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided notes only.",
            "No browsing, paid APIs, connectors, account access, or file mutation.",
        ],
        "exampleRequestBody": {
            "topic": "Local alpha reviewer notes",
            "notes": "Reviewers need a concise local-only brief. Avoid external services and validation claims.",
            "sourceTitles": ["Reviewer notes"],
            "questions": ["What should reviewers focus on?"],
            "outputType": "brief",
        },
    },
    {
        "name": "File/Data Agent",
        "endpoint": "POST /agents/files/local-summary",
        "status": "implemented_local_only",
        "mode": "local_registered_project_metadata_only",
        "docsLink": "/docs/file-data-agent.md",
        "responseMode": "metadata_only",
        "safetyNotes": [
            "Summarizes registered-project metadata only.",
            "Requires a registered project and does not accept raw arbitrary local paths.",
            "No arbitrary path scanning, protected-content reads, uploads, command execution, or mutation.",
        ],
        "exampleRequestBody": {"projectName": "Jarvis"},
    },
    {
        "name": "Local Planning Agent",
        "endpoint": "POST /agents/planning/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_planning",
        "docsLink": "/docs/local-planning-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided planning inputs only.",
            "No persistent tasks, reminders, calendar/email items, files, database records, or external calls.",
        ],
        "exampleRequestBody": {
            "goal": "Prepare a local manual smoke checklist",
            "contextNotes": "The checklist should exercise response-only agents without claiming certification.",
            "constraints": ["No external services", "No task creation"],
            "resources": ["Existing local docs"],
            "blockers": ["Needs human review"],
            "timeframe": "One local session",
            "desiredOutputType": "checklist",
        },
    },
    {
        "name": "Local Drafting Agent",
        "endpoint": "POST /agents/drafting/local-draft",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_drafting",
        "docsLink": "/docs/local-drafting-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided drafting inputs only.",
            "No draft persistence, email sending, posting, account access, file writes, or connectors.",
        ],
        "exampleRequestBody": {
            "purpose": "Draft a note for local reviewers",
            "audience": "Local manual testers",
            "notes": "Ask reviewers to try the local smoke examples and report confusing wording.",
            "tone": "clear",
            "format": "message",
            "constraints": ["No hype", "No certification claims"],
            "mustInclude": ["manual local checks only"],
            "mustAvoid": ["guaranteed"],
        },
    },
    {
        "name": "Local Review Agent",
        "endpoint": "POST /agents/review/local-review",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_review",
        "docsLink": "/docs/local-review-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided review content only.",
            "No fact verification, repo inspection, tests, persistence, file access, or connectors.",
        ],
        "exampleRequestBody": {
            "subject": "Manual smoke runbook wording",
            "content": "The runbook should be clear that checks are local and manual. It should not claim CI, clean VM validation, or certification.",
            "reviewType": "safety",
            "audience": "Local maintainers",
            "criteria": ["Clear scope", "No validation overclaims"],
            "constraints": ["No external verification claims"],
            "severity": "balanced",
        },
    },
    {
        "name": "Local Decision Agent",
        "endpoint": "POST /agents/decision/local-decision",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_decision_support",
        "docsLink": "/docs/local-decision-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided decision inputs only.",
            "No professional validation, purchases, sending, posting, persistence, file access, or external calls.",
        ],
        "exampleRequestBody": {
            "decision": "Choose a manual smoke check format",
            "options": ["Short checklist", "Long worksheet"],
            "criteria": ["Easy to repeat", "Low risk of overclaiming"],
            "constraints": ["No automation", "No external services"],
            "priorities": ["Clarity", "Safety"],
            "contextNotes": "The result should help local testers without creating persistent decisions.",
            "decisionStyle": "safest",
        },
    },
    {
        "name": "Local Troubleshooting Agent",
        "endpoint": "POST /agents/troubleshooting/local-triage",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_troubleshooting",
        "docsLink": "/docs/local-troubleshooting-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided troubleshooting inputs only.",
            "No command execution, file/log reads, repo inspection, repair actions, downloads, uploads, or mutation.",
        ],
        "exampleRequestBody": {
            "problem": "A manual smoke response looks incomplete",
            "symptoms": ["Expected safety fields are missing from the response"],
            "errorMessages": ["No error message was shown"],
            "environmentNotes": "Local Jarvis Core manual smoke session on loopback.",
            "attemptedFixes": ["Refreshed the local API client"],
            "constraints": ["No command execution", "No file inspection"],
            "urgency": "normal",
            "troubleshootingType": "workflow_issue",
        },
    },
    {
        "name": "Local Summarization Agent",
        "endpoint": "POST /agents/summarization/local-summary",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_summarization",
        "docsLink": "/docs/local-summarization-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided text only.",
            "No file reads, document retrieval, source/citation verification, persistence, repo inspection, or tests.",
        ],
        "exampleRequestBody": {
            "title": "Manual smoke notes",
            "content": "The local response agents returned structured outputs. Reviewers should check agent IDs, local-only status, and safety flags.",
            "summaryType": "bullets",
            "audience": "Local maintainers",
            "detailLevel": "medium",
            "focusAreas": ["safety fields", "manual checks"],
            "mustPreserve": ["local-only status"],
            "mustAvoid": ["certified"],
        },
    },
    {
        "name": "Local Extraction Agent",
        "endpoint": "POST /agents/extraction/local-extract",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_extraction",
        "docsLink": "/docs/local-extraction-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided text only.",
            "No file reads, document retrieval, source/citation verification, task creation, persistence, repo inspection, or tests.",
        ],
        "exampleRequestBody": {
            "title": "Manual smoke findings",
            "content": "Agent ID should match. Status should be local-only. Safety flags should show no connectors, no persistence, and no mutation.",
            "extractionType": "requirements",
            "focusAreas": ["response checks", "safety boundaries"],
            "mustCapture": ["no connectors"],
            "mustIgnore": ["certified"],
            "detailLevel": "medium",
        },
    },
    {
        "name": "Local Classification Agent",
        "endpoint": "POST /agents/classification/local-classify",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_classification",
        "docsLink": "/docs/local-classification-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided text and items only.",
            "No file reads, document retrieval, source/citation verification, task creation, agent calls, persistence, or certification.",
        ],
        "exampleRequestBody": {
            "title": "Manual smoke triage",
            "content": "README link updates are documentation work. Safety wording review is high priority.",
            "items": ["Check README link", "Review safety wording"],
            "classificationType": "priority",
            "labels": ["docs", "safety"],
            "criteria": ["manual review impact"],
            "constraints": ["no task creation"],
            "detailLevel": "medium",
        },
    },
    {
        "name": "Local Transformation Agent",
        "endpoint": "POST /agents/transformation/local-transform",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_transformation",
        "docsLink": "/docs/local-transformation-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided text and items only.",
            "No file reads/writes, document/spreadsheet/deck/export creation, persistence, repo inspection, tests, or connectors.",
        ],
        "exampleRequestBody": {
            "title": "Manual smoke notes",
            "content": "Check agent ID. Confirm local-only status. Review safety flags.",
            "items": ["Check agent ID", "Confirm local-only status", "Review safety flags"],
            "targetFormat": "checklist",
            "audience": "Local maintainers",
            "constraints": ["No file export"],
            "mustPreserve": ["local-only status"],
            "mustAvoid": ["certified"],
            "detailLevel": "medium",
        },
    },
    {
        "name": "Local Business Agent",
        "endpoint": "POST /agents/business/local-brief",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_business_planning",
        "docsLink": "/docs/local-business-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided business planning inputs only.",
            "No connector, payment, account, CRM, email, posting, purchase, persistence, file, shell, or external-service behavior.",
        ],
        "exampleRequestBody": {
            "businessName": "Neighborhood Meal Prep Studio",
            "businessIdea": "Offer small-batch weekly meal prep kits for busy local households.",
            "targetCustomer": "Busy families who want simple weeknight meals",
            "problem": "Weeknight cooking feels rushed and planning takes too much time.",
            "offer": "Pre-portioned local meal prep kits with simple instructions.",
            "pricingNotes": "Pilot a simple per-kit price and review customer feedback manually.",
            "operationsNotes": "Start with a small menu, local pickup window, and manual order tracking.",
            "marketingNotes": "Explain convenience, freshness, and predictable weekly planning.",
            "constraints": ["Manual local pilot only", "No paid ads until the offer is clearer"],
            "resources": ["Home kitchen planning notes", "Local ingredient supplier list"],
            "risks": ["Demand may be uncertain", "Operational capacity may be limited"],
            "goals": ["Validate interest manually", "Prepare a small launch checklist"],
            "desiredOutputType": "business_brief",
        },
    },
    {
        "name": "Local Health/Fitness Agent",
        "endpoint": "POST /agents/health-fitness/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_health_fitness_planning",
        "docsLink": "/docs/local-health-fitness-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided wellness, workout, habit, and nutrition-planning inputs only.",
            "No medical diagnosis, treatment plan, medication advice, supplement prescription, emergency triage, or clinical validation.",
            "No health connector, wearable, medical record, insurance, pharmacy, lab, account, persistence, file, shell, or external-service behavior.",
        ],
        "exampleRequestBody": {
            "profileName": "Local Wellness Plan",
            "primaryGoal": "Build a steady beginner strength and walking routine.",
            "currentFitnessLevel": "Beginner returning to consistent activity.",
            "ageRange": "adult",
            "heightWeightNotes": "General body-composition goals only; no clinical interpretation requested.",
            "equipmentAvailable": ["Adjustable dumbbells", "Yoga mat"],
            "preferredActivities": ["Walking", "Strength training"],
            "dislikedActivities": ["High-impact jumping"],
            "nutritionNotes": "Wants simple balanced meal planning ideas for busy days.",
            "sleepRecoveryNotes": "Wants to improve sleep consistency and avoid overdoing workouts.",
            "constraints": ["Keep sessions short", "Manual planning only"],
            "injuriesOrLimitations": ["Use conservative intensity and seek professional review for pain."],
            "habitsToBuild": ["Walk after lunch", "Prepare simple breakfast options"],
            "habitsToReduce": ["Skipping movement on busy days"],
            "desiredOutputType": "fitness_brief",
        },
    },
    {
        "name": "Local Food / Cooking / Grocery Agent",
        "endpoint": "POST /agents/food-cooking-grocery/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_food_cooking_grocery_planning",
        "docsLink": "/docs/local-food-cooking-grocery-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided meal, pantry, cooking, grocery, preference, budget, time, equipment, and leftover-planning inputs only.",
            "No grocery app, delivery app, restaurant app, health app, account, location, map, GPS, payment, file, connector, browser, or external-service behavior.",
            "No orders, purchases, reservations, persistent records, medical nutrition advice, allergy safety certainty, clinical diet prescription, weight-loss guarantee, food-safety certification, nutritionist validation, or certification claims.",
        ],
        "exampleRequestBody": {
            "request": "Make a cheap grocery list for 5 dinners using rice, eggs, chicken, frozen vegetables, and beans.",
            "outputType": "budget_grocery_plan",
            "mealGoal": "Plan 5 simple low-cost dinners.",
            "availableIngredients": ["Rice", "Eggs", "Chicken", "Frozen vegetables", "Beans"],
            "pantryItems": ["Soy sauce", "Garlic powder", "Pasta"],
            "groceryItemsNeeded": ["Tortillas", "Canned tomatoes", "Yogurt"],
            "dietaryPreferences": ["Simple high-protein meals"],
            "allergiesOrAvoidances": ["No known allergies provided"],
            "budgetLevel": "low",
            "budgetNotes": "Use pantry items first and avoid specialty ingredients.",
            "servings": "5 dinners for 1 adult",
            "timeAvailableMinutes": 30,
            "cookingSkillLevel": "beginner",
            "kitchenEquipment": ["Stove", "Skillet", "Rice cooker"],
            "mealType": "dinner",
            "cuisinePreferences": ["Flexible"],
            "leftoversOrBatchPrepGoal": "Reuse cooked rice and chicken across meals.",
            "constraintsOrNotes": "Manual planning only; no shopping app or delivery order.",
        },
    },
    {
        "name": "Local Home / Room / Living Space Agent",
        "endpoint": "POST /agents/home-room-living-space/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_home_room_living_space_planning",
        "docsLink": "/docs/local-home-room-living-space-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided room, living-space, cleaning, storage, furniture, budget, comfort, safety, and timeline notes only.",
            "No smart-home, landlord portal, utility account, store, payment, map, location, file, camera, sensor, account, connector, or external-service behavior.",
            "No purchases, mover bookings, landlord contact, maintenance requests, device control, persistence, building-code compliance, professional inspection, electrical/plumbing safety certification, pest-control certification, legal habitability determination, or certification claims.",
        ],
        "exampleRequestBody": {
            "request": "Make a small apartment room setup plan for study, sleep, storage, and exercise.",
            "outputType": "room_setup_plan",
            "roomType": "small apartment bedroom",
            "livingSituation": "Shared apartment",
            "spaceGoal": "Create zones for study, sleep, storage, and a small exercise corner.",
            "currentItems": ["Bed", "Desk", "Chair", "Laundry basket"],
            "itemsToBuyOrConsider": ["Desk lamp", "Under-bed bins", "Small shelf"],
            "budgetLevel": "low",
            "budgetNotes": "Use current items first.",
            "roomDimensionsOrConstraints": "Small room with one window and limited closet space.",
            "storageConstraints": "Clothes and school supplies pile up near the desk.",
            "cleaningOrMaintenanceNeeds": ["Weekly floor reset", "Laundry routine"],
            "aestheticPreferences": ["Calm", "Simple"],
            "productivityOrSleepGoals": ["Better study focus", "Less clutter near bed"],
            "safetyOrAccessibilityNotes": "Keep walkway clear.",
            "timeline": "Set up essentials this weekend.",
            "constraintsOrNotes": "Manual planning only; no purchases or smart-home actions.",
        },
    },
    {
        "name": "Local Legal / Immigration / Official Matters Agent",
        "endpoint": "POST /agents/legal-immigration-official/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_legal_immigration_official_planning",
        "docsLink": "/docs/local-legal-immigration-official-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided official-matter, document, deadline, agency, question, status, and urgency notes only.",
            "No government portal, immigration account, school portal, court system, legal database, email, calendar, file, payment, map, location, connector, or external-service behavior.",
            "No submissions, filings, signatures, fee payments, appointment bookings, emails, agency contact, persistence, legal advice, immigration advice, attorney review, eligibility certainty, deadline certainty, visa approval prediction, official compliance, or certification claims.",
        ],
        "exampleRequestBody": {
            "request": "Make a document checklist for an immigration appointment based only on this summary.",
            "outputType": "document_checklist",
            "matterType": "immigration appointment preparation",
            "jurisdictionOrCountryIfUserProvided": "User-provided country context only",
            "currentStatus": "User has an upcoming appointment and wants to organize documents.",
            "documentList": ["Passport", "Appointment notice", "School records", "Address history notes"],
            "deadlinesOrDates": ["Appointment date from user notes"],
            "officeOrAgencyNameIfUserProvided": "User-provided office name",
            "userQuestions": ["Which documents should I ask a qualified professional to review?"],
            "desiredOutcome": "Arrive prepared with organized questions.",
            "riskLevelOrUrgency": "Needs careful review but no emergency stated.",
            "constraintsOrNotes": "General organization only; no legal advice or filing.",
        },
    },
    {
        "name": "Local Emergency / Preparedness Agent",
        "endpoint": "POST /agents/emergency-preparedness/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_emergency_preparedness_planning",
        "docsLink": "/docs/local-emergency-preparedness-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided preparedness, household, supply, pet, vehicle, medical/accessibility, budget, communication, and constraint notes only.",
            "No emergency services, police/fire/EMS, weather service, map, GPS/location, smart device, alarm, camera, contacts, file, account, payment, connector, or external-service behavior.",
            "No emergency calls, alerts, family contact, hotel booking, supply purchases, door unlocks, device control, claim submissions, persistence, live hazard detection, official emergency guidance, evacuation-order awareness, medical triage certainty, survival guarantee, or certification claims.",
        ],
        "exampleRequestBody": {
            "request": "Make a basic car emergency kit checklist for winter driving.",
            "outputType": "car_emergency_kit",
            "scenarioType": "winter driving preparedness",
            "householdSize": "1 driver",
            "pets": [],
            "locationContextIfUserProvided": "Cold-weather driving context from user notes.",
            "currentSupplies": ["Blanket", "Phone charger", "Flashlight"],
            "vehicleOrTravelContext": "Commutes by car during winter.",
            "medicalOrAccessibilityNeeds": [],
            "budgetLevel": "low",
            "budgetNotes": "Use current supplies first.",
            "timeHorizon": "Prepare before the next cold-weather trip.",
            "communicationContactsSummary": "User will keep contact list manually.",
            "constraintsOrNotes": "Preparedness planning only; no emergency calls or purchases.",
        },
    },
    {
        "name": "Local Culture / Taste / High-Class Lifestyle Agent",
        "endpoint": "POST /agents/culture-taste-high-class-lifestyle/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_culture_taste_high_class_lifestyle_planning",
        "docsLink": "/docs/local-culture-taste-high-class-lifestyle-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided culture, taste, style, event, etiquette, budget, wardrobe, dining, conversation, and learning-interest notes only.",
            "No stores, fashion apps, reservations, restaurants, maps, location, payments, accounts, social accounts, calendar, contacts, files, camera, photos, connectors, or external-service behavior.",
            "No purchases, reservations, contacts, posts, sends, persistence, mutation, social acceptance guarantees, status guarantees, manipulation, deception, discrimination, private elite-network access, or certification claims.",
        ],
        "exampleRequestBody": {
            "request": "Prepare a respectful dinner-event polish plan based only on these notes.",
            "outputType": "event_prep_plan",
            "situationOrEvent": "Small professional dinner with unfamiliar guests",
            "cultureGoal": "Feel prepared without pretending expertise.",
            "currentStyleOrBaseline": "Usually casual, wants a cleaner and calmer presentation.",
            "desiredImpression": "Attentive, relaxed, and respectful.",
            "budgetLevel": "low",
            "budgetNotes": "Use existing wardrobe first.",
            "wardrobeOrItemsAvailable": ["Navy blazer", "Plain shirt", "Dark shoes"],
            "diningOrEventContext": "Dinner context supplied by the user; no reservation or restaurant lookup.",
            "conversationContext": "Guests may discuss books, travel, food, and local culture.",
            "readingArtMusicFilmInterests": ["Film history", "Jazz", "Architecture"],
            "etiquetteFocus": ["Introductions", "Dining pace", "Conversation balance"],
            "timeline": "One week",
            "constraintsOrNotes": "Planning only; no stores, reservations, messages, posts, or purchases.",
        },
    },
    {
        "name": "Local Hobbies / Adventure Agent",
        "endpoint": "POST /agents/hobbies-adventure/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_hobbies_adventure_planning",
        "docsLink": "/docs/local-hobbies-adventure-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided hobby, adventure, gear, budget, location-context, timing, group, transport, risk, safety, and accessibility notes only.",
            "No maps, GPS/location, weather, park systems, drone apps, fishing/license systems, booking apps, stores, payments, accounts, files, camera, sensors, connectors, or external-service behavior.",
            "No booking, buying, permit or license application, drone airspace verification, legal access verification, contacting, persistence, mutation, live safety or legal verification, unsafe stunts, trespass, poaching, vandalism, or certification claims.",
        ],
        "exampleRequestBody": {
            "request": "Create a conservative beginner weekend plan for a day hike.",
            "outputType": "weekend_plan",
            "hobbyOrActivity": "Beginner day hiking",
            "experienceLevel": "Beginner",
            "adventureGoal": "Try an easy outdoor activity without overcommitting.",
            "availableGear": ["Comfortable shoes", "Small backpack", "Water bottle"],
            "budgetLevel": "low",
            "budgetNotes": "Use available gear where safe.",
            "locationContextIfUserProvided": "User has already chosen a local beginner trail manually.",
            "timeAvailable": "Saturday morning",
            "groupSize": "2 people",
            "transportationContext": "User will arrange transport manually.",
            "riskTolerance": "Low",
            "safetyOrAccessibilityNotes": "Avoid steep or remote routes.",
            "constraintsOrNotes": "No maps, weather, park, booking, permit, purchase, or legal access verification.",
        },
    },
    {
        "name": "Local Personal Knowledge / Memory Organizer Agent",
        "endpoint": "POST /agents/personal-knowledge-memory-organizer/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_personal_knowledge_memory_organization",
        "docsLink": "/docs/local-personal-knowledge-memory-organizer-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided knowledge-area, source-note, category, project, review, priority, retention, decision, and memory-context text only.",
            "No files, notes apps, cloud drives, browser history, email, calendar, contacts, memory stores, databases, accounts, payments, connectors, or external-service behavior.",
            "No create, edit, delete, move, persist, sync, export, mutation, file search, external-memory search, secret storage, sensitive fact inference beyond provided text, or certification claims.",
        ],
        "exampleRequestBody": {
            "request": "Organize these personal learning notes into a manual memory index.",
            "outputType": "memory_index",
            "knowledgeArea": "Home lab networking notes",
            "sourceNotesOrSummary": "Router reset steps worked after checking cable labels. VLAN notes still need review. Keep troubleshooting lessons separate from purchase ideas.",
            "organizationGoal": "Find useful context quickly before the next setup session.",
            "categoriesOrTags": ["networking", "troubleshooting", "home lab"],
            "projectsOrLifeAreas": ["Home lab"],
            "reviewFrequency": "Weekly while active",
            "priorityLevel": "Medium",
            "retentionGoal": "Remember setup decisions and unresolved questions.",
            "decisionOrMemoryContext": "Future setup sessions should start with cable labels and known-good reset steps.",
            "constraintsOrNotes": "No file, notes app, database, sync, export, or persistent memory action.",
        },
    },
    {
        "name": "Local Life Dashboard / Cross-Agent Coordinator",
        "endpoint": "POST /agents/life-dashboard-coordinator/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_life_dashboard_cross_agent_coordination",
        "docsLink": "/docs/local-life-dashboard-coordinator-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided life-area, goal, project, urgent-item, time, energy, priority, decision-context, weekly-focus, and risk/stress text only.",
            "Recommends relevant local response agents by name or id as suggestions only; no automatic sub-agent execution, handoffs, connector calls, account access, external services, persistence, tasks, reminders, file mutation, email, calendar, social posting, purchase, booking, submission, payment, official filing, emergency, medical, legal, or financial action.",
            "High-stakes topics are framed as planning notes only and point users toward qualified professionals or official sources without certainty claims.",
        ],
        "exampleRequestBody": {
            "request": "Turn my school, robotics, fitness, money, and social goals into a weekly life dashboard.",
            "outputType": "life_dashboard",
            "lifeAreas": ["School", "Robotics", "Fitness", "Money", "Social"],
            "currentGoals": ["Keep classes on track", "Prepare the robotics build", "Restart workouts", "Stay inside the weekly budget"],
            "currentProjects": ["Robotics competition", "Semester assignments", "Meal prep reset"],
            "urgentItems": ["Math quiz Friday", "Robot drivetrain test", "Budget check before weekend"],
            "timeHorizon": "Next 7 days",
            "availableTime": "Two evenings and Saturday morning",
            "energyLevel": "Medium with lower energy after school",
            "constraintsOrNotes": "No calendar, task, reminder, file, connector, or account access.",
            "priorityPreference": "Balance urgent school work with robotics progress.",
            "domainsToCoordinate": ["school", "robotics", "fitness", "money", "relationships"],
            "existingAgentOutputsOrNotes": ["Study plan needs a short review block", "Budget notes are user-provided only"],
            "decisionContext": "Choose where to spend limited evening focus.",
            "weeklyFocus": "Protect school deadlines while making visible robotics progress.",
            "riskOrStressFlags": ["Overcommitting", "Skipping rest"],
            "desiredDashboardStyle": "Compact weekly dashboard",
        },
    },
    {
        "name": "Local Everyday Life Agent",
        "endpoint": "POST /agents/everyday-life/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_everyday_life_planning",
        "docsLink": "/docs/local-everyday-life-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided everyday-life planning inputs only.",
            "No calendar, task, email, contact, map, location, finance, smart-home, health-app, account, connector, persistence, file, shell, purchase, post, or message behavior.",
            "Suggestions only; no validation, automation, scheduling, delivery, completion, or execution claims.",
        ],
        "exampleRequestBody": {
            "lifeArea": "Household reset",
            "situation": "Prepare for a busy week with chores, errands, and personal admin.",
            "goals": ["Reduce clutter", "Batch errands", "Set up simple evening routines"],
            "constraints": ["Keep the plan manual", "Avoid adding new apps or accounts"],
            "scheduleNotes": "Two short evening blocks and one weekend planning block.",
            "householdNotes": "Shared spaces need a quick reset before the week starts.",
            "errands": ["Return library books", "Pick up basic groceries"],
            "peopleInvolved": ["Household members"],
            "resources": ["Existing checklist", "Reusable bags"],
            "energyNotes": "Energy is lower after work, so keep weekday steps small.",
            "budgetNotes": "Use items already on hand where possible.",
            "desiredOutputType": "life_brief",
        },
    },
    {
        "name": "Local Online Presence Agent",
        "endpoint": "POST /agents/online-presence/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_online_presence_planning",
        "docsLink": "/docs/local-online-presence-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided online presence planning and drafting inputs only.",
            "Drafting only; no posting, scheduling, messaging, scraping, analytics, live profile verification, account access, or connector behavior.",
            "No brand success, follower growth, hiring result, reputation verification, platform compliance review, public posting, persistence, file, shell, or external-service behavior.",
        ],
        "exampleRequestBody": {
            "profileName": "Local Portfolio Profile",
            "platforms": ["Portfolio site", "Professional profile"],
            "currentBio": "Builder of practical local-first tools and documentation.",
            "goals": ["Clarify positioning", "Draft profile copy", "Plan a few content ideas"],
            "targetAudience": "Collaborators and reviewers interested in local-first software",
            "tone": "Clear, grounded, and practical",
            "strengths": ["Local-first product thinking", "Careful documentation", "Review-friendly implementation"],
            "projects": ["Local assistant dashboard", "Manual evidence runbooks"],
            "contentIdeas": ["Explain a local-only design choice", "Share a short project lesson"],
            "constraints": ["No hype", "No live profile verification"],
            "reputationConcerns": ["Avoid unsupported claims"],
            "desiredOutputType": "presence_brief",
        },
    },
    {
        "name": "Local Security/Safety Agent",
        "endpoint": "POST /agents/security-safety/local-review",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_security_safety_review",
        "docsLink": "/docs/local-security-safety-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided security and safety review inputs only.",
            "No scans, commands, account access, file reads, secret reads, browser/cookie access, password-manager access, downloads, remediation, or connector behavior.",
            "No hacking, exploit, evasion, malware, phishing, unauthorized-access help, forensic validation, legal validation, compliance certification, or security certification.",
        ],
        "exampleRequestBody": {
            "reviewName": "Local Account Hygiene Review",
            "situation": "Prepare a manual safety review for a personal account and shared device after a suspicious message.",
            "assetsOrAccounts": ["Personal email account", "Shared laptop"],
            "concerns": ["Suspicious message", "Unclear recovery settings"],
            "currentControls": ["Two-step sign-in is believed to be enabled"],
            "constraints": ["No account access from Jarvis", "No scans or downloads"],
            "riskTolerance": "Cautious",
            "environmentNotes": "Use only user-provided notes for a local checklist.",
            "incidentNotes": "No active emergency reported; prepare notes for manual review.",
            "desiredOutputType": "safety_brief",
        },
    },
    {
        "name": "Local Creator Agent",
        "endpoint": "POST /agents/creator/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_creator_planning",
        "docsLink": "/docs/local-creator-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided creator, channel, video, and content planning inputs only.",
            "Drafting and planning only; no YouTube, social platform, account, analytics, upload, posting, scheduling, scraping, messaging, persistence, file, shell, or external-service behavior.",
            "No follower growth, monetization success, trend validation, copyright clearance, brand deal validation, platform compliance, algorithm certainty, or certification claims.",
        ],
        "exampleRequestBody": {
            "creatorName": "Local Workshop Channel",
            "platforms": ["Video channel", "Short-form clips"],
            "niche": "Local-first software workflows",
            "audience": "Builders who want practical local tools",
            "contentIdea": "Explain how a local-only planning assistant stays review-friendly.",
            "goals": ["Clarify the idea", "Draft an outline", "Plan repurposing options"],
            "tone": "Practical and clear",
            "formatNotes": "Short explainer with a simple three-part structure.",
            "productionResources": ["Screen notes", "Demo outline"],
            "constraints": ["No platform claims", "No live trend verification"],
            "existingContentNotes": "Previous notes focus on local-only boundaries and manual review.",
            "desiredOutputType": "creator_brief",
        },
    },
    {
        "name": "Local School / Robotics Agent",
        "endpoint": "POST /agents/school-robotics/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_school_robotics_planning",
        "docsLink": "/docs/local-school-robotics-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided school, Northeastern, robotics, research, course, co-op, project, and study-planning notes only.",
            "Planning and drafting only; no school portal, registrar, Handshake, financial-aid, email, calendar, course catalog, professor website, GitHub, file, shell, account, connector, paid API, or external-service behavior.",
            "No registration, submission, sending, live verification, persistence, official academic validation, admission, enrollment, co-op, professor-response, research-placement, graduation, employment, or certification claims.",
        ],
        "exampleRequestBody": {
            "studentName": "Local Student",
            "schoolName": "Northeastern",
            "programName": "Robotics-focused engineering plan",
            "termOrTimeline": "Next two academic terms",
            "academicGoal": "Prepare for robotics research, Vascular-Twin planning, and a stronger co-op search.",
            "roboticsFocus": "Robot perception, controls, simulation, and applied health robotics.",
            "courses": ["Robotics foundations", "Computer vision", "Control systems"],
            "professorsOrLabs": ["User-provided robotics lab note", "User-provided health robotics research note"],
            "projects": ["Vascular-Twin planning prototype", "Small robot perception demo"],
            "constraints": ["Manual planning only", "No live course availability verification"],
            "resources": ["Advisor notes", "Campus career center notes", "Robotics club notes"],
            "currentPreparation": "Completed introductory programming and early robotics reading.",
            "desiredOutputType": "school_brief",
        },
    },
    {
        "name": "Local Career / Job Search Agent",
        "endpoint": "POST /agents/career/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_career_planning",
        "docsLink": "/docs/local-career-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided career goals, resume notes, job targets, co-op or internship plans, interview prep, networking notes, skills, projects, and constraints only.",
            "Planning and drafting only; no LinkedIn, Handshake, job-board, email, calendar, contact, school portal, account, GitHub, file, shell, connector, paid API, or external-service behavior.",
            "No applying, submitting, messaging, scheduling, resume upload, scraping, browsing, live verification, persistence, official career validation, legal validation, job placement, interview, hiring, salary, or certification claims.",
        ],
        "exampleRequestBody": {
            "profileName": "Local Career Profile",
            "careerGoal": "Prepare for robotics software internships and co-op conversations.",
            "targetRoles": ["Robotics software intern", "Computer vision intern"],
            "targetIndustries": ["Robotics", "Health technology"],
            "currentExperience": "Course projects and local planning work in robotics and software.",
            "educationNotes": "Engineering student building robotics and applied software experience.",
            "skills": ["Python", "C++", "Computer vision", "Controls", "Technical writing"],
            "projects": ["Vascular-Twin planning prototype", "Robot perception demo"],
            "resumeNotes": "Emphasize project evidence, measurable scope, and manual review wording.",
            "jobSearchNotes": "Focus on a small manually reviewed target list.",
            "networkingNotes": "Prepare respectful informational conversation scripts.",
            "constraints": ["Manual planning only", "No live job-board verification"],
            "desiredOutputType": "career_brief",
        },
    },
    {
        "name": "Local Finance / Loans / Budget Agent",
        "endpoint": "POST /agents/finance-budget/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_finance_budget_planning",
        "docsLink": "/docs/local-finance-budget-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided finance, budget, student-loan, debt, rent, move-cost, cash-flow, savings, and spending notes only.",
            "Planning and checklists only; no bank, credit-card, loan-servicer, brokerage, payment, tax, financial-aid, account, file, shell, connector, paid API, or external-service behavior.",
            "No payments, transfers, trades, purchases, applications, submissions, account connections, statement reads, live verification, persistence, financial advice validation, tax validation, legal validation, investment validation, accounting validation, loan approval, repayment certainty, or certification claims.",
        ],
        "exampleRequestBody": {
            "profileName": "Local Finance Plan",
            "financialGoal": "Prepare a manual budget for Boston move costs, student loans, and savings.",
            "incomeNotes": "Monthly income estimate from user-provided notes only.",
            "expenseNotes": "Recurring food, transit, phone, utilities, and school-related costs.",
            "debtNotes": "Student loan and small revolving balance notes for manual review.",
            "loanNotes": "Student loan repayment options need official servicer confirmation.",
            "rentHousingNotes": "Compare rent affordability for shared Boston housing.",
            "moveCostNotes": "Estimate deposit, first month, moving supplies, and transit setup.",
            "savingsNotes": "Build a small emergency cushion before optional spending.",
            "spendingNotes": "Review dining out, subscriptions, and hobby spending manually.",
            "constraints": ["Manual planning only", "No account connections or live balance checks"],
            "priorities": ["Avoid missed payments", "Protect move-in cash cushion"],
            "desiredOutputType": "finance_brief",
        },
    },
    {
        "name": "Local Housing / Move / Travel Agent",
        "endpoint": "POST /agents/housing-move-travel/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_housing_move_travel_planning",
        "docsLink": "/docs/local-housing-move-travel-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided housing, move, commute, setup, budget, transportation, and travel notes only.",
            "Planning, comparisons, and checklists only; no apartment sites, maps, listings, booking platforms, school portals, email, calendar, contacts, accounts, lease systems, payments, files, connectors, paid APIs, or external-service behavior.",
            "No bookings, reservations, lease signing, applications, landlord messaging, tour scheduling, payments, ticket purchases, live availability, current prices, neighborhood safety validation, legal lease review, housing approval, commute-time certainty, persistence, mutation, or certification claims.",
        ],
        "exampleRequestBody": {
            "planName": "Boston Move Plan",
            "destination": "Boston campus area",
            "housingGoal": "Compare user-provided housing options and prepare a manual move checklist.",
            "timeline": "Move before the fall term starts",
            "budgetNotes": "Estimate rent, deposit, utilities, moving supplies, travel, and emergency buffer manually.",
            "housingOptions": ["Shared apartment near transit", "Student housing option from user notes"],
            "moveItems": ["Laptop and chargers", "Clothes", "Bedding", "Important documents"],
            "transportationNotes": "Compare driving with shipped boxes against flying with checked bags.",
            "commuteNotes": "Review walking, transit, and backup commute assumptions from user notes.",
            "utilitySetupNotes": "Internet, mail forwarding, renter insurance, and move-in inspection need manual confirmation.",
            "constraints": ["Manual planning only", "No live listings or map checks"],
            "priorities": ["Protect budget buffer", "Keep commute reliable", "Avoid rushed move-in"],
            "desiredOutputType": "move_brief",
        },
    },
    {
        "name": "Local Projects / Portfolio Agent",
        "endpoint": "POST /agents/projects-portfolio/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_projects_portfolio_planning",
        "docsLink": "/docs/local-projects-portfolio-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided project, portfolio, skill, proof artifact, audience, role, constraint, priority, and timeline notes only.",
            "Planning, drafting, and prioritization only; no GitHub, repo, file, project registry, source-code, commit, branch, website, analytics, resume, account, connector, paid API, or external-service inspection.",
            "No file creation, repo edits, issues, commits, pushes, uploads, publishing, submissions, scraping, browsing, persistence, mutation, live GitHub verification, portfolio quality certification, hiring outcome certainty, code review validation, project completion, official validation, or certification claims.",
        ],
        "exampleRequestBody": {
            "profileName": "Local Portfolio Profile",
            "portfolioGoal": "Prepare a project portfolio plan for robotics software internship conversations.",
            "targetAudience": "Recruiters and technical reviewers reading user-provided portfolio notes.",
            "targetRoles": ["Robotics software intern", "Computer vision intern"],
            "projectNotes": ["Vascular-Twin planning prototype", "Robot perception demo", "Local Jarvis response-agent work"],
            "skills": ["Python", "C++", "Computer vision", "Technical writing"],
            "proofArtifacts": ["Case study draft", "Demo outline", "Screenshot checklist"],
            "currentStatus": "Projects need clearer summaries and manually reviewed proof artifacts.",
            "constraints": ["Manual planning only", "No repo or GitHub inspection"],
            "priorities": ["Show technical depth", "Keep claims human-reviewed", "Make proof easy to scan"],
            "timeline": "Prepare a first portfolio pass before internship outreach.",
            "desiredOutputType": "portfolio_brief",
        },
    },
    {
        "name": "Local Learning / Study Coach Agent",
        "endpoint": "POST /agents/learning-study/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_learning_study_planning",
        "docsLink": "/docs/local-learning-study-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided learning goals, topics, current level, schedule notes, resources, weak areas, habits, and review needs only.",
            "Planning, prompts, drills, and checklists only; no school portal, LMS, textbook, website, file, calendar, task app, Anki, Notion, Google Drive, GitHub, account, connector, paid API, or external-service behavior.",
            "No browsing, scraping, downloads, external flashcard creation, calendar events, task creation, study-record persistence, assignment submission, official tutoring, course credit, grade guarantee, exam score guarantee, academic validation, mastery validation, or certification claims.",
        ],
        "exampleRequestBody": {
            "learnerName": "Local Learner",
            "learningGoal": "Build a steady study plan for robotics controls and computer vision foundations.",
            "topics": ["PID control", "State estimation", "Image filtering", "Camera calibration"],
            "currentLevel": "Comfortable with programming basics; weaker on math-heavy explanations.",
            "timeline": "Prepare over the next six weeks before project work intensifies.",
            "availableTime": "Four 45-minute blocks during the week and one weekend review block.",
            "resources": ["Class notes", "Practice problem set", "User-provided project notes"],
            "weakAreas": ["Deriving equations", "Explaining assumptions", "Remembering formulas"],
            "preferredMethods": ["Active recall", "Practice problems", "Feynman explanations"],
            "constraints": ["Manual planning only", "No LMS or calendar connection"],
            "motivationNotes": "Connect each study block to stronger robotics project confidence.",
            "desiredOutputType": "learning_brief",
        },
    },
    {
        "name": "Local Social / Networking / High-Class Coach Agent",
        "endpoint": "POST /agents/social-networking/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_social_networking_planning",
        "docsLink": "/docs/local-social-networking-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided social, networking, etiquette, event-prep, conversation, presentation, presence, and comfort notes only.",
            "Planning, scripts, drafts, and checklists only; no contacts, email, calendar, social platform, DM, message, profile, location, camera, microphone, file, account, connector, paid API, or external-service behavior.",
            "No sending, scheduling, posting, scraping, tracking, private-information identification, persistence, task creation, mutation, manipulation, coercion, deception, harassment, stalking, doxxing, impersonation, evasion, social outcome guarantee, reputation verification, or etiquette certification claims.",
        ],
        "exampleRequestBody": {
            "profileName": "Local Social Profile",
            "socialGoal": "Prepare for a polished robotics networking reception with respectful conversation and follow-up options.",
            "setting": "University networking reception",
            "peopleContext": "Students, alumni, professors, and robotics industry guests may attend.",
            "eventNotes": "Short conversations, light refreshments, and informal introductions after a project showcase.",
            "conversationTopics": ["Robotics projects", "Career paths", "Research interests"],
            "networkingGoals": ["Practice concise introductions", "Ask thoughtful questions", "Identify welcome follow-up opportunities"],
            "presentationNotes": "Aim for calm, clear, and sincere rather than flashy.",
            "constraints": ["Manual planning only", "No contact, email, calendar, or social platform access"],
            "comfortLevel": "Somewhat nervous but willing to practice.",
            "desiredOutputType": "social_brief",
        },
    },
    {
        "name": "Local Personal Admin / Documents Agent",
        "endpoint": "POST /agents/personal-admin/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_personal_admin_planning",
        "docsLink": "/docs/local-personal-admin-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided personal admin goals, document types, deadlines, requirements, current status, offices, constraints, and notes only.",
            "Planning, checklists, draft organization, and readiness review only; no document, file, ID, PDF, email, calendar, portal, account, cloud drive, school system, loan system, government site, connector, paid API, or external-service behavior.",
            "No form submission, email sending, appointment scheduling, reminder or task creation, upload, signing, payment, persistence, file mutation, legal validation, tax validation, immigration validation, school validation, loan validation, government validation, identity validation, official submission validation, or certification claims.",
        ],
        "exampleRequestBody": {
            "profileName": "Local Admin Profile",
            "adminGoal": "Prepare a manual checklist for school forms and loan paperwork before an office appointment.",
            "documentTypes": ["School enrollment form", "Loan deferment paperwork", "Photo ID copy checklist"],
            "deadlines": ["Forms due before the next advising appointment", "Loan paperwork review needed this month"],
            "requirements": ["Confirm required fields", "List supporting records", "Mark signature fields", "Prepare questions for the office"],
            "currentStatus": "Forms are gathered but not fully reviewed.",
            "constraints": ["Manual planning only", "No file, portal, email, calendar, or cloud-drive access"],
            "peopleOrOfficesInvolved": ["School advising office", "Loan servicer help desk"],
            "notes": "User wants a calm readiness review before submitting anything outside Jarvis.",
            "desiredOutputType": "admin_brief",
        },
    },
    {
        "name": "Local Vehicle / Devices / Gear Agent",
        "endpoint": "POST /agents/vehicle-devices-gear/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_vehicle_devices_gear_planning",
        "docsLink": "/docs/local-vehicle-devices-gear-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided vehicle, device, drone, scooter, gear, maintenance, troubleshooting, packing, setup, inventory, constraint, and priority notes only.",
            "Planning, checklists, inventory, and non-executing troubleshooting suggestions only; no device, vehicle, drone, file, OS setting, app, account, OBD, Bluetooth, Wi-Fi, GPS/location, map, controller, warranty portal, repair portal, connector, paid API, or external-service behavior.",
            "No diagnostics, commands, repairs, updates, resets, downloads, purchases, bookings, flight actions, device control, vehicle control, scans, persistence, mutation, mechanic validation, electrical safety validation, flight legality, warranty validation, live airspace or map verification, repair certainty, data recovery certainty, or certification claims.",
        ],
        "exampleRequestBody": {
            "profileName": "Local Gear Profile",
            "gearGoal": "Prepare a manual readiness checklist for a campus project day with laptop, scooter, and drone gear.",
            "vehicleNotes": "Car may be used for transport; confirm tire pressure and fuel manually before leaving.",
            "deviceNotes": "Laptop, phone, chargers, portable battery, and camera need a pre-trip check.",
            "droneScooterNotes": "Drone and scooter should be reviewed only after checking local rules and battery condition manually.",
            "inventoryItems": ["Laptop", "Phone", "Chargers", "Portable battery", "Camera", "Drone case", "Scooter helmet"],
            "maintenanceConcerns": ["Battery condition", "Tire pressure", "Loose accessories"],
            "troubleshootingNotes": "Phone battery has drained quickly recently; avoid destructive troubleshooting.",
            "packingNotes": "Pack light but include backup charging and safety gear.",
            "constraints": ["Manual planning only", "No diagnostics, device control, vehicle control, maps, or flight actions"],
            "priorities": ["Safety", "Battery readiness", "Reliable project capture"],
            "desiredOutputType": "gear_brief",
        },
    },
    {
        "name": "Local Life Direction / Values Agent",
        "endpoint": "POST /agents/life-direction/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_life_direction_planning",
        "docsLink": "/docs/local-life-direction-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided life direction, values, long-term goals, identity, standards, priorities, discipline, tradeoff, constraint, strength, growth-area, non-negotiable, and reflection notes only.",
            "Planning, reflection prompts, standards, and checklists only; no files, journals, calendars, tasks, accounts, messages, health data, finance data, school portals, contacts, connector, paid API, or external-service behavior.",
            "No goal persistence, task creation, reminder creation, event scheduling, messaging, public posting, purchases, file mutation, therapy claim, mental-health diagnosis, treatment plan, crisis intervention, legal advice, financial advice, medical advice, spiritual authority, guaranteed success, life-outcome certainty, or certification claims.",
        ],
        "exampleRequestBody": {
            "profileName": "Local Direction Profile",
            "lifeQuestion": "Clarify the next season across school, career, money, health, projects, relationships, and personal growth.",
            "currentSeason": "Building technical skill, preparing career options, and trying to become more disciplined without burning out.",
            "values": ["Competence", "Integrity", "Health", "Family", "Creative independence"],
            "longTermGoals": ["Become a strong technical builder", "Create durable projects", "Build stable finances"],
            "currentPriorities": ["School progress", "Portfolio projects", "Health habits"],
            "tensionsOrTradeoffs": ["Ambition versus rest", "Many project ideas versus finishing a few"],
            "constraints": ["Manual reflection only", "No calendar, task, account, health, finance, or school portal access"],
            "areasToImprove": ["Consistency", "Focus", "Follow-through"],
            "strengths": ["Curiosity", "Systems thinking", "Persistence"],
            "nonNegotiables": ["No fake claims", "Protect health", "Keep commitments realistic"],
            "reflectionNotes": "User wants a grounded season plan and standards, not therapy or guaranteed outcomes.",
            "desiredOutputType": "life_direction_brief",
        },
    },
    {
        "name": "Local Relationship / Family Agent",
        "endpoint": "POST /agents/relationships/local-plan",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_relationship_planning",
        "docsLink": "/docs/local-relationships-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided relationship goal, relationship type, people context, situation notes, communication goals, concerns, boundaries, desired tone, and constraints only.",
            "Planning, conversation scripts, drafts, checklists, boundary language, check-in plans, occasion ideas, and maintenance notes only; no contacts, messages, DMs, email, calendar, social platforms, location, photos, files, accounts, connectors, paid APIs, or external-service behavior.",
            "No sending, scheduling, posting, scraping, tracking, private-information identification, persistence, task creation, mutation, manipulation, coercion, deception, harassment, stalking, doxxing, impersonation, jealousy-control, evasion guidance, therapy claims, diagnosis, treatment plans, relationship outcome certainty, conflict resolution guarantees, legal validation, safety validation, emotional certainty, or certification claims.",
        ],
        "exampleRequestBody": {
            "profileName": "Local Relationship Profile",
            "relationshipGoal": "Prepare a respectful check-in conversation with a family member about improving communication.",
            "relationshipType": "Family",
            "peopleContext": "The user wants to talk with a family member after several tense conversations.",
            "situationNotes": "The goal is to lower tension, ask for clearer expectations, and avoid blame.",
            "communicationGoals": ["Open calmly", "Ask what would help", "Agree on one next step"],
            "concerns": ["Conversation may become defensive", "Avoid sounding accusatory"],
            "boundaries": ["Pause if voices rise", "No name-calling"],
            "desiredTone": "Warm, direct, and low-pressure",
            "constraints": ["Manual planning only", "No messages, calendar access, contacts, or external services"],
            "desiredOutputType": "relationship_brief",
        },
    },
    {
        "name": "Local Emotional Reflection / Resilience Agent",
        "endpoint": "POST /agents/emotional-reflection/local-reflect",
        "status": "implemented_local_only",
        "mode": "response_only_user_provided_emotional_reflection",
        "docsLink": "/docs/local-emotional-reflection-agent.md",
        "responseMode": "response_only",
        "safetyNotes": [
            "Uses user-provided emotional reflection, stress, motivation, discipline recovery, confidence, journaling, resilience, mood, energy, win, challenge, pattern, support-option, and constraint notes only.",
            "Reflection prompts, coping checklists, self-review, and planning only; no journal, file, health-record, message, contact, account, calendar, task, wearable, connector, paid API, browsing, or external-service behavior.",
            "No persistence, task creation, reminder creation, messaging, appointment scheduling, contact action, file mutation, therapy claims, diagnosis, treatment plans, crisis intervention, medical advice, psychiatric advice, medication advice, medical validation, psychiatric validation, mental-health validation, outcome guarantees, or certification claims.",
        ],
        "exampleRequestBody": {
            "profileName": "Local Reflection Profile",
            "reflectionGoal": "Reset after a stressful school and project week without turning it into self-criticism.",
            "currentMoodNotes": "Tired, frustrated, and trying to regain momentum.",
            "stressors": ["Behind on study plan", "Project uncertainty", "Low sleep"],
            "energyNotes": "Energy is better in the morning and lower after dinner.",
            "recentWins": ["Finished one project task", "Asked for clarification", "Went for a walk"],
            "currentChallenges": ["Restarting discipline", "Avoiding all-or-nothing thinking"],
            "patternsNoticed": ["Overcommits when motivated", "Skips recovery after hard days"],
            "supportOptions": ["Talk with a trusted person", "Use campus support if distress worsens"],
            "constraints": ["Manual reflection only", "No journals, health records, messages, contacts, calendars, tasks, or external services"],
            "desiredOutputType": "reflection_brief",
        },
    },
]

LOCAL_RESPONSE_AGENTS_GLOBAL_BOUNDARIES = [
    "No paid APIs.",
    "No connectors.",
    "No OAuth or account access.",
    "No browser automation.",
    "No cloud sync.",
    "No file mutation except existing Coding Agent workflows.",
    "No email sending, posting, or purchases.",
    "No task persistence for response-only agents.",
    "Optional read-only public URL source context is available only when the user explicitly enables it; no background browsing.",
    "Reviewed web_context source excerpts are manual, optional, non-persistent, and agents do not auto-browse.",
    "Source labels are for reference, not proof, certification, or source authority validation.",
    "Source-aware response sections use reviewed excerpts only and do not claim browsing, live verification, or independent fact-checking.",
    "No claims of clean Windows VM validation, CI validation, private-alpha certification, production readiness, or security certification.",
]


def local_response_agents_index() -> list[dict[str, Any]]:
    return [enrich_local_response_agent(agent) for agent in deepcopy(LOCAL_RESPONSE_AGENTS_INDEX)]


def local_response_agents_global_boundaries() -> list[str]:
    return list(LOCAL_RESPONSE_AGENTS_GLOBAL_BOUNDARIES)


def local_response_agents_summary() -> dict[str, Any]:
    agents = local_response_agents_index()
    return {
        "status": "read_only_index",
        "agentCount": len(agents),
        "expectedAgentCount": LOCAL_RESPONSE_AGENT_COUNT,
        "agents": agents,
        "globalBoundaries": local_response_agents_global_boundaries(),
        "docsLink": "/docs/local-response-agents-index.md",
        "addsAgents": False,
        "addsEndpoint": False,
        "mutation": False,
        "connectorExecution": False,
        "paidApis": False,
        "oauth": False,
        "accountAccess": False,
        "browserAutomation": False,
        "cloudSync": False,
        "emailSendingPostingPurchases": False,
        "taskPersistenceForResponseOnlyAgents": False,
        "webResearchAvailable": True,
        "web_research_available": True,
        "webResearchMode": WEB_RESEARCH_AGENT_MODE,
        "web_research_mode": WEB_RESEARCH_AGENT_MODE,
        "webResearchRequiresUserEnabled": True,
        "web_research_requires_user_enabled": True,
        "webResearchIsOptional": True,
        "web_research_is_optional": True,
        "webResearchLimitations": list(WEB_RESEARCH_LIMITATIONS),
        "web_research_limitations": list(WEB_RESEARCH_LIMITATIONS),
        "webContextSupported": True,
        "web_context_supported": True,
        "webContextIsOptional": True,
        "web_context_is_optional": True,
        "webContextIsNonPersistent": True,
        "web_context_is_non_persistent": True,
        "webResearchRequiresManualFetch": True,
        "web_research_requires_manual_fetch": True,
        "agentsDoNotAutoBrowse": True,
        "agents_do_not_auto_browse": True,
        "sourceEvidenceSupported": True,
        "source_evidence_supported": True,
        "citationLabelsSupported": True,
        "citation_labels_supported": True,
        "sourceRecencyFlagsSupported": True,
        "source_recency_flags_supported": True,
        "sourceAwareResponseSupported": True,
        "source_aware_response_supported": True,
        "webContextLimitations": list(WEB_CONTEXT_RESPONSE_LIMITATIONS),
        "web_context_limitations": list(WEB_CONTEXT_RESPONSE_LIMITATIONS),
        "certificationClaims": False,
    }


def local_response_agents_discovery_catalog() -> dict[str, Any]:
    agents = local_response_agents_index()
    return {
        "status": "local_response_agents_discovery_catalog",
        "agent_count": len(agents),
        "agentCount": len(agents),
        "expected_agent_count": LOCAL_RESPONSE_AGENT_COUNT,
        "expectedAgentCount": LOCAL_RESPONSE_AGENT_COUNT,
        "agents": [discovery_metadata_for_agent(agent) for agent in agents],
        "consistency": validate_catalog_consistency(agents),
        "local_only": True,
        "manual_input_only": True,
        "response_only": True,
        "non_persistent": True,
        "connector_behavior": False,
        "web_research_available": True,
        "webResearchAvailable": True,
        "web_research_mode": WEB_RESEARCH_AGENT_MODE,
        "webResearchMode": WEB_RESEARCH_AGENT_MODE,
        "web_research_requires_user_enabled": True,
        "webResearchRequiresUserEnabled": True,
        "web_research_is_optional": True,
        "webResearchIsOptional": True,
        "web_context_supported": True,
        "webContextSupported": True,
        "web_context_is_optional": True,
        "webContextIsOptional": True,
        "web_context_is_non_persistent": True,
        "webContextIsNonPersistent": True,
        "web_research_requires_manual_fetch": True,
        "webResearchRequiresManualFetch": True,
        "agents_do_not_auto_browse": True,
        "agentsDoNotAutoBrowse": True,
        "source_evidence_supported": True,
        "sourceEvidenceSupported": True,
        "citation_labels_supported": True,
        "citationLabelsSupported": True,
        "source_recency_flags_supported": True,
        "sourceRecencyFlagsSupported": True,
        "source_aware_response_supported": True,
        "sourceAwareResponseSupported": True,
    }


def local_response_agent_categories() -> dict[str, Any]:
    return list_local_agent_categories(local_response_agents_index())


def local_response_agent_metadata(agent_id: str) -> dict[str, Any]:
    return get_local_agent_metadata(agent_id, local_response_agents_index())


def local_response_agent_request_template(agent_id: str) -> dict[str, Any]:
    return build_local_agent_request_template(agent_id, local_response_agents_index())


def local_response_agent_route_preview(
    text: str,
    domains_to_consider: list[str] | None = None,
    preferred_output_type: str = "",
    urgency_level: str = "",
    constraints_or_notes: str = "",
) -> dict[str, Any]:
    return preview_local_agent_route(
        text,
        domains_to_consider or [],
        preferred_output_type,
        urgency_level,
        constraints_or_notes,
        local_response_agents_index(),
    )


def local_response_agent_manual_workflow_preview(
    user_goal: str,
    candidate_agent_ids: list[str] | None = None,
    route_preview_suggestions: list[Any] | None = None,
    max_steps: int = 4,
    include_web_context: bool = False,
    constraints_or_notes: str = "",
) -> dict[str, Any]:
    return preview_manual_agent_workflow(
        user_goal,
        candidate_agent_ids or [],
        route_preview_suggestions or [],
        max_steps,
        include_web_context,
        constraints_or_notes,
        local_response_agents_index(),
    )
